import Foundation

// MARK: - 定律宇宙 数据（少而精，每条都是「通透卡」）

enum LawLibrary {
    static let all: [PhysicsLaw] = [
        PhysicsLaw(
            id: "newton2",
            name: "牛顿第二定律",
            nameEN: "Newton's Second Law",
            topic: .newton,
            stage: .senior,
            expression: "F合 = ma",
            dimension: "N = kg·m/s²",
            physicalImage: "力不是「维持」运动的，而是「改变」运动的——踢一脚球，球变速；不踢，它就匀速跑下去。",
            derivation: "由动量定义 p=mv 与「力是动量的变化率」F=Δp/Δt 出发，质量不变时就化简成 F=ma。它和动量定理本是同一句话。",
            meaning: "合外力决定加速度。力的方向就是加速度的方向，跟速度方向无关。",
            limitChecks: [
                LimitCheck(scenario: "合力 F → 0", result: "a → 0，速度保持不变", intuition: "不受力就匀速或静止——这正是牛顿第一定律。原来一、二定律是一家人。"),
                LimitCheck(scenario: "质量 m → 很大", result: "同样的力，a → 很小", intuition: "推汽车几乎推不动：质量就是「惰性」的度量，越大越难改变运动。"),
            ],
            conditions: ["惯性参考系", "宏观低速（远小于光速）", "质量恒定"],
            commonMisuses: ["把「有力」当成「有速度」——其实力对应的是加速度", "在非惯性系直接用（需补惯性力）"],
            applications: ["连接体问题", "斜面 / 传送带", "牛顿定律 + 圆周运动"],
            relatedWeapons: [.forceDiagram, .workEnergyTheorem]
        ),
        PhysicsLaw(
            id: "momentum_conservation",
            name: "动量守恒定律",
            nameEN: "Conservation of Momentum",
            topic: .momentum,
            stage: .senior,
            expression: "p前 = p后，即 Σmᵢvᵢ = 常量",
            dimension: "kg·m/s",
            physicalImage: "一群人在光滑冰面上推来推去，不管怎么折腾，整体的「总动量账本」纹丝不动。",
            derivation: "来自牛顿第三定律：内力总是成对出现、等大反向，彼此抵消，所以系统总动量不会被内力改变。",
            meaning: "系统合外力为零时，总动量守恒——碰撞 / 爆炸题的上帝视角，无视中间过程多复杂。",
            limitChecks: [
                LimitCheck(scenario: "等质量弹性正碰", result: "两球交换速度", intuition: "台球母球撞上静止球，自己停下、把速度「传」过去——守恒律的经典画面。"),
                LimitCheck(scenario: "撞墙：墙的质量 M → ∞", result: "小球原速反弹，墙几乎不动", intuition: "墙改变不了自己的速度，只把小球弹回去——极端质量比下的直觉。"),
            ],
            conditions: ["系统所受合外力为零", "或：碰撞 / 爆炸瞬间内力远大于外力", "矢量式，注意方向与正负"],
            commonMisuses: ["把动量守恒误当动能守恒（非弹性碰撞动能会损失）", "只在某一方向守恒时当成整体守恒"],
            applications: ["碰撞", "反冲 / 爆炸", "人船模型"],
            relatedWeapons: [.momentumConservation, .referenceFrame]
        ),
        PhysicsLaw(
            id: "mechanical_energy",
            name: "机械能守恒定律",
            nameEN: "Conservation of Mechanical Energy",
            topic: .energy,
            stage: .senior,
            expression: "Ek + Ep = 常量",
            dimension: "J = kg·m²/s²",
            physicalImage: "过山车——爬高时把动能「存」成势能，俯冲时再「取」回来，总账始终不变（没摩擦的话）。",
            derivation: "重力做的功 = 动能的增量（动能定理），而重力做功又等于势能的减少，两者一搭，机械能总量就守恒。",
            meaning: "只有重力 / 弹力做功时，动能与势能相互转化、总量不变。",
            limitChecks: [
                LimitCheck(scenario: "从高 h 自由下落到底", result: "v = √(2gh)，与质量无关", intuition: "真空中羽毛和铁球同速落地——mgh = ½mv² 两边的 m 约掉了。"),
                LimitCheck(scenario: "单摆摆到最低点", result: "速度最大、势能最低", intuition: "能量在两种形式间倒来倒去，此消彼长，最低点动能全满。"),
            ],
            conditions: ["只有重力和弹力做功", "其他力不做功", "系统无摩擦生热"],
            commonMisuses: ["有摩擦 / 空气阻力时仍套守恒", "势能零点选取前后不一致"],
            applications: ["竖直圆周 / 单摆", "弹簧问题", "过山车类问题"],
            relatedWeapons: [.mechanicalEnergy, .energyIntuition]
        ),
        PhysicsLaw(
            id: "work_energy",
            name: "动能定理",
            nameEN: "Work–Energy Theorem",
            topic: .energy,
            stage: .senior,
            expression: "W合 = ½mv₂² − ½mv₁²",
            dimension: "J = N·m",
            physicalImage: "合力做的功，像往「动能账户」里存钱或取钱——余额的变化就是末动能减初动能。",
            derivation: "把 F=ma 沿位移累加（积分）：∫F dx = ∫ma dx = ½mv² 的变化。它是牛顿定律的「能量版」。",
            meaning: "合外力做的功等于动能的变化——不管路径多曲折、力是否变化，只看功的总和。",
            limitChecks: [
                LimitCheck(scenario: "合力做功 = 0", result: "动能不变，速率不变", intuition: "匀速圆周运动里向心力永远垂直速度、不做功，所以速率恒定。"),
                LimitCheck(scenario: "只有摩擦力做负功", result: "动能持续减少直到停下", intuition: "滑行的物体终会停——动能被摩擦「吃掉」变成了热。"),
            ],
            conditions: ["适用于任何力（含变力、摩擦力）", "标量式，功有正负"],
            commonMisuses: ["漏掉摩擦力做的负功", "把「路程」当「位移」算功"],
            applications: ["变力做功", "曲线运动求末速度", "多过程问题一步跨越"],
            relatedWeapons: [.workEnergyTheorem, .energyIntuition]
        ),
        PhysicsLaw(
            id: "lorentz",
            name: "洛伦兹力",
            nameEN: "Lorentz Force",
            topic: .magnetic,
            stage: .senior,
            expression: "F = qvB·sinθ",
            dimension: "N（B 的单位 T = kg/(A·s²)）",
            physicalImage: "磁场像个「拐弯器」——它只改变带电粒子的方向，从不给它提速。",
            derivation: "实验定律 F = qv×B。因为力永远垂直于速度，它在速度方向上的分量为零，所以改变方向却不改变速率。",
            meaning: "磁场对运动电荷的作用力，方向由左手 / 右手定则判定，恒垂直于速度。",
            limitChecks: [
                LimitCheck(scenario: "速度 v 平行于磁场 B", result: "F = 0，粒子直线穿过", intuition: "顺着磁场跑不拐弯——sinθ = 0，磁场对它「视而不见」。"),
                LimitCheck(scenario: "速度 v 垂直于 B", result: "做匀速圆周，半径 r = mv/qB", intuition: "恒垂直的力正好当向心力，画出一个完美的圆。"),
            ],
            conditions: ["电荷在磁场中运动", "θ 为 v 与 B 的夹角"],
            commonMisuses: ["以为洛伦兹力会做功（它永远不做功）", "v 平行 B 时仍以为有力"],
            applications: ["带电粒子圆周运动", "回旋加速器", "质谱仪"],
            relatedWeapons: [.crossProduct, .symmetry]
        ),
        PhysicsLaw(
            id: "gravitation",
            name: "万有引力定律",
            nameEN: "Law of Universal Gravitation",
            topic: .circular,
            stage: .senior,
            expression: "F = GMm/r²",
            dimension: "N（G ≈ 6.67×10⁻¹¹ N·m²/kg²）",
            physicalImage: "任何两个有质量的物体都在互相吸引——连你和手机之间也有，只是太弱察觉不到。",
            derivation: "牛顿意识到「苹果落地」和「月球绕地」是同一种力，再结合开普勒定律，反推出与距离平方成反比。",
            meaning: "质量是引力之源，距离越远引力越弱（平方反比）。",
            limitChecks: [
                LimitCheck(scenario: "距离 r → 2 倍", result: "引力 → 1/4", intuition: "平方反比衰减极快，这就是近地与高轨卫星受力差别巨大的原因。"),
                LimitCheck(scenario: "其中一个质量 → 0", result: "引力 → 0", intuition: "没有质量就没有引力源——质量是引力的唯一通行证。"),
            ],
            conditions: ["质点或均匀球体", "r 为两球心间距", "对任何有质量物体成立"],
            commonMisuses: ["把 r 当成表面间距（应是球心间距）", "对非球对称物体直接套用"],
            applications: ["天体运动", "卫星环绕", "黄金代换 GM=gR²"],
            relatedWeapons: [.equivalentMethod, .symmetry]
        ),
        PhysicsLaw(
            id: "circular_force",
            name: "向心力",
            nameEN: "Centripetal Force",
            topic: .circular,
            stage: .senior,
            expression: "F = mv²/r = mω²r",
            dimension: "N",
            physicalImage: "让物体拐弯的力，永远指向圆心——绳拉小球转圈，绳的拉力就是它。",
            derivation: "匀速圆周里速度方向时刻在变，即有指向圆心的加速度 a=v²/r，乘上质量就是向心力。",
            meaning: "向心力是「效果命名」，由真实的力（张力 / 重力 / 摩擦 / 洛伦兹力）提供，不是额外的力。",
            limitChecks: [
                LimitCheck(scenario: "速度 v → 2 倍（半径不变）", result: "向心力 → 4 倍", intuition: "高速过弯特别危险，因为力随 v² 暴涨。"),
                LimitCheck(scenario: "半径 r → ∞", result: "向心力 → 0", intuition: "走直线不需要向心力——圆周与直线在此平滑统一。"),
            ],
            conditions: ["匀速圆周时向心力 = 合力", "一般圆周取合力指向圆心的分量"],
            commonMisuses: ["在受力图里额外画一个「向心力」", "把向心力当成新产生的力"],
            applications: ["圆锥摆", "竖直圆周临界", "带电粒子圆周"],
            relatedWeapons: [.forceDiagram, .symmetry]
        ),
        PhysicsLaw(
            id: "impulse",
            name: "动量定理",
            nameEN: "Impulse–Momentum Theorem",
            topic: .momentum,
            stage: .senior,
            expression: "Ft = mv₂ − mv₁",
            dimension: "N·s = kg·m/s",
            physicalImage: "同样改变动量，把时间拖长就能减小冲力——安全气囊、跳远落沙坑全靠它。",
            derivation: "由 F=ma=mΔv/Δt 两边乘 Δt 得到，是牛顿第二定律的「时间累积版」。",
            meaning: "合力的冲量等于动量的变化，矢量式。",
            limitChecks: [
                LimitCheck(scenario: "作用时间 t → 很长（缓冲）", result: "平均力 F → 很小", intuition: "气囊把碰撞时间拉长，冲力骤降——这就是保命的物理。"),
                LimitCheck(scenario: "作用时间 t → 0（硬碰）", result: "冲力 → 极大", intuition: "鸡蛋落地瞬间停下冲力大到碎；落到棉花上时间长就没事。"),
            ],
            conditions: ["适用于变力（用平均力或冲量）", "矢量式，注意方向"],
            commonMisuses: ["把冲量当成力", "漏掉矢量方向的正负"],
            applications: ["缓冲问题", "流体冲击", "反冲"],
            relatedWeapons: [.momentumConservation]
        ),
        PhysicsLaw(
            id: "coulomb",
            name: "库仑定律",
            nameEN: "Coulomb's Law",
            topic: .electricField,
            stage: .senior,
            expression: "F = kq₁q₂/r²",
            dimension: "N（k ≈ 9×10⁹ N·m²/C²）",
            physicalImage: "电荷版的「万有引力」——同种相斥、异种相吸，同样是平方反比。",
            derivation: "库仑用扭秤实验测出，形式和万有引力惊人地一致，宇宙偏爱平方反比。",
            meaning: "点电荷间作用力与电量乘积成正比、与距离平方成反比。",
            limitChecks: [
                LimitCheck(scenario: "距离 r → 2 倍", result: "力 → 1/4", intuition: "和万有引力一样的平方反比，自然界两种基本力共用一个数学骨架。"),
                LimitCheck(scenario: "其中一个电荷 → 0", result: "力 → 0", intuition: "中性物体间没有库仑力（极化感应是进阶话题）。"),
            ],
            conditions: ["点电荷", "真空或空气中", "r 为电荷间距"],
            commonMisuses: ["对带电体（非点电荷）直接套用", "忘了力是矢量、要叠加"],
            applications: ["电荷平衡", "三电荷共线", "类比引力"],
            relatedWeapons: [.symmetry, .equivalentMethod]
        ),
        PhysicsLaw(
            id: "ohm",
            name: "欧姆定律",
            nameEN: "Ohm's Law",
            topic: .circuit,
            stage: .senior,
            expression: "I = U/R",
            dimension: "A = V/Ω",
            physicalImage: "电压是「水压」、电流是「水流」、电阻是「水管粗细」——压越大流越快，管越细流越慢。",
            derivation: "欧姆用大量实验总结出的经验定律，对恒温金属导体成立。",
            meaning: "电流正比于电压、反比于电阻。",
            limitChecks: [
                LimitCheck(scenario: "电阻 R → 2 倍（电压不变）", result: "电流 → 一半", intuition: "限流就靠加大电阻——反比关系一目了然。"),
                LimitCheck(scenario: "电阻 R → 0（短路）", result: "电流 → ∞（理论上）", intuition: "短路电流极大极危险，现实里被电源内阻和保险丝拦住。"),
            ],
            conditions: ["纯电阻、恒温", "金属导体", "U、I、R 对应同一段电路"],
            commonMisuses: ["对非线性元件（灯丝、二极管）套用", "U、I、R 张冠李戴"],
            applications: ["电路计算", "串并联", "伏安法测电阻"],
            relatedWeapons: [.equivalentCircuit]
        ),
        PhysicsLaw(
            id: "closed_circuit",
            name: "闭合电路欧姆定律",
            nameEN: "Ohm's Law for Complete Circuit",
            topic: .circuit,
            stage: .senior,
            expression: "E = I(R + r)，U端 = E − Ir",
            dimension: "V",
            physicalImage: "电源像个「带内耗的水泵」——电动势是它的总本事，内阻悄悄吃掉一部分。",
            derivation: "能量守恒：电源做的功 = 外电路 + 内电路消耗，两边除以电荷量即得。",
            meaning: "电动势等于内外电压之和；路端电压随电流增大而下降。",
            limitChecks: [
                LimitCheck(scenario: "外阻 R → ∞（断路）", result: "I→0，U端 → E", intuition: "断路时电压表读数约等于电动势。"),
                LimitCheck(scenario: "外阻 R → 0（短路）", result: "I → E/r（最大），U端 → 0", intuition: "短路电流由内阻决定，路端电压为零。"),
            ],
            conditions: ["闭合回路", "r 为电源内阻"],
            commonMisuses: ["忽略内阻", "把路端电压当成恒定电动势"],
            applications: ["电源 U-I 图象", "测电动势与内阻", "电路动态分析"],
            relatedWeapons: [.graphMethod]
        ),
        PhysicsLaw(
            id: "ampere",
            name: "安培力",
            nameEN: "Ampère's Force",
            topic: .magnetic,
            stage: .senior,
            expression: "F = BIL·sinθ",
            dimension: "N",
            physicalImage: "磁场推「电流」的力——电动机转起来，就是无数根通电导线被磁场推动。",
            derivation: "安培力是导线中所有运动电荷所受洛伦兹力的宏观合力。",
            meaning: "磁场对通电导线的作用力，方向用左手定则。",
            limitChecks: [
                LimitCheck(scenario: "电流方向平行磁场（θ=0）", result: "F = 0", intuition: "顺着磁场的电流不受力。"),
                LimitCheck(scenario: "电流垂直磁场（θ=90°）", result: "F = BIL（最大）", intuition: "电动机里导线都尽量垂直磁场摆放，力最大。"),
            ],
            conditions: ["θ 为电流与 B 的夹角", "匀强磁场中的直导线"],
            commonMisuses: ["与洛伦兹力公式混用", "左手定则方向判错"],
            applications: ["电动机", "磁电式电表", "安培天平"],
            relatedWeapons: [.crossProduct]
        ),
        PhysicsLaw(
            id: "faraday",
            name: "法拉第电磁感应定律",
            nameEN: "Faraday's Law of Induction",
            topic: .induction,
            stage: .senior,
            expression: "E = n·ΔΦ/Δt（切割式 E = BLv）",
            dimension: "V",
            physicalImage: "磁场「变化」才生电——磁铁插进线圈的那一下来电，停着不动就没电。",
            derivation: "法拉第的实验定律，本质是变化的磁场会激发涡旋电场。",
            meaning: "感应电动势正比于磁通量的变化率，而不是磁通量本身。",
            limitChecks: [
                LimitCheck(scenario: "磁通量不变（ΔΦ=0）", result: "E = 0", intuition: "磁铁停在线圈里，再强也不来电——「变化」才是关键。"),
                LimitCheck(scenario: "变化越快（Δt → 小）", result: "E 越大", intuition: "发电机转得越快、磁铁抽插越急，电压越高。"),
            ],
            conditions: ["闭合回路", "Φ 为穿过回路的磁通量"],
            commonMisuses: ["把 E 与 Φ 划等号（应是变化率）", "漏掉匝数 n"],
            applications: ["发电机", "变压器", "感应加热"],
            relatedWeapons: [.lenzRule, .graphMethod]
        ),
        PhysicsLaw(
            id: "gas_law",
            name: "理想气体状态方程",
            nameEN: "Ideal Gas Law",
            topic: .thermal,
            stage: .senior,
            expression: "pV/T = 常量",
            dimension: "pV 的量纲是能量 J",
            physicalImage: "一定量气体的「压强×体积÷温度」是个守恒的账本——挤小体积，压强或温度必涨。",
            derivation: "由玻意耳、查理、盖-吕萨克三条实验定律合并而来。",
            meaning: "一定质量理想气体三个状态量之间的约束关系。",
            limitChecks: [
                LimitCheck(scenario: "体积 V → 一半（温度不变）", result: "压强 → 2 倍", intuition: "打气筒按下去，气体被压、压强升高。"),
                LimitCheck(scenario: "温度 T → 升高（体积不变）", result: "压强 → 升高", intuition: "密闭罐受热会爆，就是这个原因。"),
            ],
            conditions: ["一定质量、理想气体", "温度必须用开尔文 K", "三量同时只能定两个"],
            commonMisuses: ["温度误用摄氏度", "气体质量变化时套用"],
            applications: ["活塞问题", "封闭气柱", "气压计"],
            relatedWeapons: [.controlVariable]
        ),
        PhysicsLaw(
            id: "photo_equation",
            name: "光电效应方程",
            nameEN: "Photoelectric Equation",
            topic: .modern,
            stage: .senior,
            expression: "Ek = hν − W₀",
            dimension: "J（或 eV）",
            physicalImage: "光子像一颗子弹，能量 hν 砸向电子；先付「逸出费」W₀，剩下的才变成电子的动能。",
            derivation: "爱因斯坦的光量子假说：光以 hν 的能量包传递，对单个电子用能量守恒即得。",
            meaning: "光电子的最大初动能 = 光子能量 − 逸出功。",
            limitChecks: [
                LimitCheck(scenario: "频率 ν → 截止频率（hν=W₀）", result: "Ek → 0", intuition: "刚好够「付费」就能打出电子，但它跑不动。"),
                LimitCheck(scenario: "光强增大（频率不变）", result: "Ek 不变，只是电子更多", intuition: "光强管数量、频率管能量——光电效应的铁律。"),
            ],
            conditions: ["hν > W₀ 才发生", "W₀ 由金属种类决定"],
            commonMisuses: ["以为光强影响最大初动能", "用波动观点解释（解释不了截止频率）"],
            applications: ["光电管", "验证普朗克常量", "截止电压"],
            relatedWeapons: [.energyIntuition]
        ),
        PhysicsLaw(
            id: "refraction",
            name: "折射定律",
            nameEN: "Law of Refraction",
            topic: .optics,
            stage: .senior,
            expression: "n = sinθ₁/sinθ₂；全反射 sinC = 1/n",
            dimension: "折射率 n 无量纲",
            physicalImage: "光进入更「密」的介质会变慢、并向法线偏折——像车斜着开进泥地，靠泥一侧先慢，车头就偏了。",
            derivation: "光在不同介质中速度不同（n=c/v），由惠更斯原理或费马原理导出。",
            meaning: "入射角与折射角正弦之比等于折射率，是光速比的体现。",
            limitChecks: [
                LimitCheck(scenario: "光密→光疏，入射角 > 临界角", result: "折射光消失，全反射", intuition: "光纤靠它把光锁在纤芯里，几乎无损耗地传输。"),
                LimitCheck(scenario: "入射角 → 0（垂直入射）", result: "折射角 → 0，不偏折", intuition: "正对着看水里的物体方向不变，只是显得浅。"),
            ],
            conditions: ["两种均匀介质的界面", "角度从法线量起"],
            commonMisuses: ["把全反射方向搞反（必须光密→光疏）", "角度误从界面量起"],
            applications: ["光纤", "海市蜃楼", "玻璃砖测折射率"],
            relatedWeapons: [.symmetry]
        ),
    ]

    static func laws(for topic: PhysicsTopic) -> [PhysicsLaw] {
        all.filter { $0.topic == topic }
    }
}
