import Foundation

// MARK: - 定律宇宙 数据（少而精，每条都是「通透卡」）

enum LawLibrary {
    static let all: [PhysicsLaw] = [
        PhysicsLaw(
            id: "newton2",
            name: "牛顿第二定律",
            nameEN: "Newton's Second Law",
            topic: .newton,
            stage: .senior,
            expression: "F合 = ma",
            dimension: "N = kg·m/s²",
            physicalImage: "力不是「维持」运动的，而是「改变」运动的——踢一脚球，球变速；不踢，它就匀速跑下去。",
            derivation: "由动量定义 p=mv 与「力是动量的变化率」F=Δp/Δt 出发，质量不变时就化简成 F=ma。它和动量定理本是同一句话。",
            meaning: "合外力决定加速度。力的方向就是加速度的方向，跟速度方向无关。",
            limitChecks: [
                LimitCheck(scenario: "合力 F → 0", result: "a → 0，速度保持不变", intuition: "不受力就匀速或静止——这正是牛顿第一定律。原来一、二定律是一家人。"),
                LimitCheck(scenario: "质量 m → 很大", result: "同样的力，a → 很小", intuition: "推汽车几乎推不动：质量就是「惰性」的度量，越大越难改变运动。"),
            ],
            conditions: ["惯性参考系", "宏观低速（远小于光速）", "质量恒定"],
            commonMisuses: ["把「有力」当成「有速度」——其实力对应的是加速度", "在非惯性系直接用（需补惯性力）"],
            applications: ["连接体问题", "斜面 / 传送带", "牛顿定律 + 圆周运动"],
            relatedWeapons: [.forceDiagram, .workEnergyTheorem],
            latex: "\\vec{F}_{\\text{合}} = m\\vec{a}"
        ),
        PhysicsLaw(
            id: "momentum_conservation",
            name: "动量守恒定律",
            nameEN: "Conservation of Momentum",
            topic: .momentum,
            stage: .senior,
            expression: "p前 = p后，即 Σmᵢvᵢ = 常量",
            dimension: "kg·m/s",
            physicalImage: "一群人在光滑冰面上推来推去，不管怎么折腾，整体的「总动量账本」纹丝不动。",
            derivation: "来自牛顿第三定律：内力总是成对出现、等大反向，彼此抵消，所以系统总动量不会被内力改变。",
            meaning: "系统合外力为零时，总动量守恒——碰撞 / 爆炸题的上帝视角，无视中间过程多复杂。",
            limitChecks: [
                LimitCheck(scenario: "等质量弹性正碰", result: "两球交换速度", intuition: "台球母球撞上静止球，自己停下、把速度「传」过去——守恒律的经典画面。"),
                LimitCheck(scenario: "撞墙：墙的质量 M → ∞", result: "小球原速反弹，墙几乎不动", intuition: "墙改变不了自己的速度，只把小球弹回去——极端质量比下的直觉。"),
            ],
            conditions: ["系统所受合外力为零", "或：碰撞 / 爆炸瞬间内力远大于外力", "矢量式，注意方向与正负"],
            commonMisuses: ["把动量守恒误当动能守恒（非弹性碰撞动能会损失）", "只在某一方向守恒时当成整体守恒"],
            applications: ["碰撞", "反冲 / 爆炸", "人船模型"],
            relatedWeapons: [.momentumConservation, .referenceFrame],
            latex: "\\sum m_i \\vec{v}_i = \\text{常量}"
        ),
        PhysicsLaw(
            id: "mechanical_energy",
            name: "机械能守恒定律",
            nameEN: "Conservation of Mechanical Energy",
            topic: .energy,
            stage: .senior,
            expression: "Ek + Ep = 常量",
            dimension: "J = kg·m²/s²",
            physicalImage: "过山车——爬高时把动能「存」成势能，俯冲时再「取」回来，总账始终不变（没摩擦的话）。",
            derivation: "重力做的功 = 动能的增量（动能定理），而重力做功又等于势能的减少，两者一搭，机械能总量就守恒。",
            meaning: "只有重力 / 弹力做功时，动能与势能相互转化、总量不变。",
            limitChecks: [
                LimitCheck(scenario: "从高 h 自由下落到底", result: "v = √(2gh)，与质量无关", intuition: "真空中羽毛和铁球同速落地——mgh = ½mv² 两边的 m 约掉了。"),
                LimitCheck(scenario: "单摆摆到最低点", result: "速度最大、势能最低", intuition: "能量在两种形式间倒来倒去，此消彼长，最低点动能全满。"),
            ],
            conditions: ["只有重力和弹力做功", "其他力不做功", "系统无摩擦生热"],
            commonMisuses: ["有摩擦 / 空气阻力时仍套守恒", "势能零点选取前后不一致"],
            applications: ["竖直圆周 / 单摆", "弹簧问题", "过山车类问题"],
            relatedWeapons: [.mechanicalEnergy, .energyIntuition],
            latex: "E_k + E_p = \\text{常量}"
        ),
        PhysicsLaw(
            id: "work_energy",
            name: "动能定理",
            nameEN: "Work–Energy Theorem",
            topic: .energy,
            stage: .senior,
            expression: "W合 = ½mv₂² − ½mv₁²",
            dimension: "J = N·m",
            physicalImage: "合力做的功，像往「动能账户」里存钱或取钱——余额的变化就是末动能减初动能。",
            derivation: "把 F=ma 沿位移累加（积分）：∫F dx = ∫ma dx = ½mv² 的变化。它是牛顿定律的「能量版」。",
            meaning: "合外力做的功等于动能的变化——不管路径多曲折、力是否变化，只看功的总和。",
            limitChecks: [
                LimitCheck(scenario: "合力做功 = 0", result: "动能不变，速率不变", intuition: "匀速圆周运动里向心力永远垂直速度、不做功，所以速率恒定。"),
                LimitCheck(scenario: "只有摩擦力做负功", result: "动能持续减少直到停下", intuition: "滑行的物体终会停——动能被摩擦「吃掉」变成了热。"),
            ],
            conditions: ["适用于任何力（含变力、摩擦力）", "标量式，功有正负"],
            commonMisuses: ["漏掉摩擦力做的负功", "把「路程」当「位移」算功"],
            applications: ["变力做功", "曲线运动求末速度", "多过程问题一步跨越"],
            relatedWeapons: [.workEnergyTheorem, .energyIntuition],
            latex: "W_{\\text{合}} = \\tfrac{1}{2}mv_2^2 - \\tfrac{1}{2}mv_1^2"
        ),
        PhysicsLaw(
            id: "lorentz",
            name: "洛伦兹力",
            nameEN: "Lorentz Force",
            topic: .magnetic,
            stage: .senior,
            expression: "F = qvB·sinθ",
            dimension: "N（B 的单位 T = kg/(A·s²)）",
            physicalImage: "磁场像个「拐弯器」——它只改变带电粒子的方向，从不给它提速。",
            derivation: "实验定律 F = qv×B。因为力永远垂直于速度，它在速度方向上的分量为零，所以改变方向却不改变速率。",
            meaning: "磁场对运动电荷的作用力，方向由左手 / 右手定则判定，恒垂直于速度。",
            limitChecks: [
                LimitCheck(scenario: "速度 v 平行于磁场 B", result: "F = 0，粒子直线穿过", intuition: "顺着磁场跑不拐弯——sinθ = 0，磁场对它「视而不见」。"),
                LimitCheck(scenario: "速度 v 垂直于 B", result: "做匀速圆周，半径 r = mv/qB", intuition: "恒垂直的力正好当向心力，画出一个完美的圆。"),
            ],
            conditions: ["电荷在磁场中运动", "θ 为 v 与 B 的夹角"],
            commonMisuses: ["以为洛伦兹力会做功（它永远不做功）", "v 平行 B 时仍以为有力"],
            applications: ["带电粒子圆周运动", "回旋加速器", "质谱仪"],
            relatedWeapons: [.crossProduct, .symmetry],
            latex: "F = qvB\\sin\\theta"
        ),
        PhysicsLaw(
            id: "gravitation",
            name: "万有引力定律",
            nameEN: "Law of Universal Gravitation",
            topic: .circular,
            stage: .senior,
            expression: "F = GMm/r²",
            dimension: "N（G ≈ 6.67×10⁻¹¹ N·m²/kg²）",
            physicalImage: "任何两个有质量的物体都在互相吸引——连你和手机之间也有，只是太弱察觉不到。",
            derivation: "牛顿意识到「苹果落地」和「月球绕地」是同一种力，再结合开普勒定律，反推出与距离平方成反比。",
            meaning: "质量是引力之源，距离越远引力越弱（平方反比）。",
            limitChecks: [
                LimitCheck(scenario: "距离 r → 2 倍", result: "引力 → 1/4", intuition: "平方反比衰减极快，这就是近地与高轨卫星受力差别巨大的原因。"),
                LimitCheck(scenario: "其中一个质量 → 0", result: "引力 → 0", intuition: "没有质量就没有引力源——质量是引力的唯一通行证。"),
            ],
            conditions: ["质点或均匀球体", "r 为两球心间距", "对任何有质量物体成立"],
            commonMisuses: ["把 r 当成表面间距（应是球心间距）", "对非球对称物体直接套用"],
            applications: ["天体运动", "卫星环绕", "黄金代换 GM=gR²"],
            relatedWeapons: [.equivalentMethod, .symmetry],
            latex: "F = G\\dfrac{Mm}{r^2}"
        ),
        PhysicsLaw(
            id: "circular_force",
            name: "向心力",
            nameEN: "Centripetal Force",
            topic: .circular,
            stage: .senior,
            expression: "F = mv²/r = mω²r",
            dimension: "N",
            physicalImage: "让物体拐弯的力，永远指向圆心——绳拉小球转圈，绳的拉力就是它。",
            derivation: "匀速圆周里速度方向时刻在变，即有指向圆心的加速度 a=v²/r，乘上质量就是向心力。",
            meaning: "向心力是「效果命名」，由真实的力（张力 / 重力 / 摩擦 / 洛伦兹力）提供，不是额外的力。",
            limitChecks: [
                LimitCheck(scenario: "速度 v → 2 倍（半径不变）", result: "向心力 → 4 倍", intuition: "高速过弯特别危险，因为力随 v² 暴涨。"),
                LimitCheck(scenario: "半径 r → ∞", result: "向心力 → 0", intuition: "走直线不需要向心力——圆周与直线在此平滑统一。"),
            ],
            conditions: ["匀速圆周时向心力 = 合力", "一般圆周取合力指向圆心的分量"],
            commonMisuses: ["在受力图里额外画一个「向心力」", "把向心力当成新产生的力"],
            applications: ["圆锥摆", "竖直圆周临界", "带电粒子圆周"],
            relatedWeapons: [.forceDiagram, .symmetry],
            latex: "F = \\dfrac{mv^2}{r} = m\\omega^2 r"
        ),
        PhysicsLaw(
            id: "impulse",
            name: "动量定理",
            nameEN: "Impulse–Momentum Theorem",
            topic: .momentum,
            stage: .senior,
            expression: "Ft = mv₂ − mv₁",
            dimension: "N·s = kg·m/s",
            physicalImage: "同样改变动量，把时间拖长就能减小冲力——安全气囊、跳远落沙坑全靠它。",
            derivation: "由 F=ma=mΔv/Δt 两边乘 Δt 得到，是牛顿第二定律的「时间累积版」。",
            meaning: "合力的冲量等于动量的变化，矢量式。",
            limitChecks: [
                LimitCheck(scenario: "作用时间 t → 很长（缓冲）", result: "平均力 F → 很小", intuition: "气囊把碰撞时间拉长，冲力骤降——这就是保命的物理。"),
                LimitCheck(scenario: "作用时间 t → 0（硬碰）", result: "冲力 → 极大", intuition: "鸡蛋落地瞬间停下冲力大到碎；落到棉花上时间长就没事。"),
            ],
            conditions: ["适用于变力（用平均力或冲量）", "矢量式，注意方向"],
            commonMisuses: ["把冲量当成力", "漏掉矢量方向的正负"],
            applications: ["缓冲问题", "流体冲击", "反冲"],
            relatedWeapons: [.momentumConservation],
            latex: "\\vec{F}t = m\\vec{v}_2 - m\\vec{v}_1"
        ),
        PhysicsLaw(
            id: "coulomb",
            name: "库仑定律",
            nameEN: "Coulomb's Law",
            topic: .electricField,
            stage: .senior,
            expression: "F = kq₁q₂/r²",
            dimension: "N（k ≈ 9×10⁹ N·m²/C²）",
            physicalImage: "电荷版的「万有引力」——同种相斥、异种相吸，同样是平方反比。",
            derivation: "库仑用扭秤实验测出，形式和万有引力惊人地一致，宇宙偏爱平方反比。",
            meaning: "点电荷间作用力与电量乘积成正比、与距离平方成反比。",
            limitChecks: [
                LimitCheck(scenario: "距离 r → 2 倍", result: "力 → 1/4", intuition: "和万有引力一样的平方反比，自然界两种基本力共用一个数学骨架。"),
                LimitCheck(scenario: "其中一个电荷 → 0", result: "力 → 0", intuition: "中性物体间没有库仑力（极化感应是进阶话题）。"),
            ],
            conditions: ["点电荷", "真空或空气中", "r 为电荷间距"],
            commonMisuses: ["对带电体（非点电荷）直接套用", "忘了力是矢量、要叠加"],
            applications: ["电荷平衡", "三电荷共线", "类比引力"],
            relatedWeapons: [.symmetry, .equivalentMethod],
            latex: "F = k\\dfrac{q_1 q_2}{r^2}"
        ),
        PhysicsLaw(
            id: "ohm",
            name: "欧姆定律",
            nameEN: "Ohm's Law",
            topic: .circuit,
            stage: .senior,
            expression: "I = U/R",
            dimension: "A = V/Ω",
            physicalImage: "电压是「水压」、电流是「水流」、电阻是「水管粗细」——压越大流越快，管越细流越慢。",
            derivation: "欧姆用大量实验总结出的经验定律，对恒温金属导体成立。",
            meaning: "电流正比于电压、反比于电阻。",
            limitChecks: [
                LimitCheck(scenario: "电阻 R → 2 倍（电压不变）", result: "电流 → 一半", intuition: "限流就靠加大电阻——反比关系一目了然。"),
                LimitCheck(scenario: "电阻 R → 0（短路）", result: "电流 → ∞（理论上）", intuition: "短路电流极大极危险，现实里被电源内阻和保险丝拦住。"),
            ],
            conditions: ["纯电阻、恒温", "金属导体", "U、I、R 对应同一段电路"],
            commonMisuses: ["对非线性元件（灯丝、二极管）套用", "U、I、R 张冠李戴"],
            applications: ["电路计算", "串并联", "伏安法测电阻"],
            relatedWeapons: [.equivalentCircuit],
            latex: "I = \\dfrac{U}{R}"
        ),
        PhysicsLaw(
            id: "closed_circuit",
            name: "闭合电路欧姆定律",
            nameEN: "Ohm's Law for Complete Circuit",
            topic: .circuit,
            stage: .senior,
            expression: "E = I(R + r)，U端 = E − Ir",
            dimension: "V",
            physicalImage: "电源像个「带内耗的水泵」——电动势是它的总本事，内阻悄悄吃掉一部分。",
            derivation: "能量守恒：电源做的功 = 外电路 + 内电路消耗，两边除以电荷量即得。",
            meaning: "电动势等于内外电压之和；路端电压随电流增大而下降。",
            limitChecks: [
                LimitCheck(scenario: "外阻 R → ∞（断路）", result: "I→0，U端 → E", intuition: "断路时电压表读数约等于电动势。"),
                LimitCheck(scenario: "外阻 R → 0（短路）", result: "I → E/r（最大），U端 → 0", intuition: "短路电流由内阻决定，路端电压为零。"),
            ],
            conditions: ["闭合回路", "r 为电源内阻"],
            commonMisuses: ["忽略内阻", "把路端电压当成恒定电动势"],
            applications: ["电源 U-I 图象", "测电动势与内阻", "电路动态分析"],
            relatedWeapons: [.graphMethod],
            latex: "E = I(R+r),\\quad U_{\\text{端}} = E - Ir"
        ),
        PhysicsLaw(
            id: "ampere",
            name: "安培力",
            nameEN: "Ampère's Force",
            topic: .magnetic,
            stage: .senior,
            expression: "F = BIL·sinθ",
            dimension: "N",
            physicalImage: "磁场推「电流」的力——电动机转起来，就是无数根通电导线被磁场推动。",
            derivation: "安培力是导线中所有运动电荷所受洛伦兹力的宏观合力。",
            meaning: "磁场对通电导线的作用力，方向用左手定则。",
            limitChecks: [
                LimitCheck(scenario: "电流方向平行磁场（θ=0）", result: "F = 0", intuition: "顺着磁场的电流不受力。"),
                LimitCheck(scenario: "电流垂直磁场（θ=90°）", result: "F = BIL（最大）", intuition: "电动机里导线都尽量垂直磁场摆放，力最大。"),
            ],
            conditions: ["θ 为电流与 B 的夹角", "匀强磁场中的直导线"],
            commonMisuses: ["与洛伦兹力公式混用", "左手定则方向判错"],
            applications: ["电动机", "磁电式电表", "安培天平"],
            relatedWeapons: [.crossProduct],
            latex: "F = BIL\\sin\\theta"
        ),
        PhysicsLaw(
            id: "faraday",
            name: "法拉第电磁感应定律",
            nameEN: "Faraday's Law of Induction",
            topic: .induction,
            stage: .senior,
            expression: "E = n·ΔΦ/Δt（切割式 E = BLv）",
            dimension: "V",
            physicalImage: "磁场「变化」才生电——磁铁插进线圈的那一下来电，停着不动就没电。",
            derivation: "法拉第的实验定律，本质是变化的磁场会激发涡旋电场。",
            meaning: "感应电动势正比于磁通量的变化率，而不是磁通量本身。",
            limitChecks: [
                LimitCheck(scenario: "磁通量不变（ΔΦ=0）", result: "E = 0", intuition: "磁铁停在线圈里，再强也不来电——「变化」才是关键。"),
                LimitCheck(scenario: "变化越快（Δt → 小）", result: "E 越大", intuition: "发电机转得越快、磁铁抽插越急，电压越高。"),
            ],
            conditions: ["闭合回路", "Φ 为穿过回路的磁通量"],
            commonMisuses: ["把 E 与 Φ 划等号（应是变化率）", "漏掉匝数 n"],
            applications: ["发电机", "变压器", "感应加热"],
            relatedWeapons: [.lenzRule, .graphMethod],
            latex: "E = n\\dfrac{\\Delta\\Phi}{\\Delta t}\\quad (E = BLv)"
        ),
        PhysicsLaw(
            id: "gas_law",
            name: "理想气体状态方程",
            nameEN: "Ideal Gas Law",
            topic: .thermal,
            stage: .senior,
            expression: "pV/T = 常量",
            dimension: "pV 的量纲是能量 J",
            physicalImage: "一定量气体的「压强×体积÷温度」是个守恒的账本——挤小体积，压强或温度必涨。",
            derivation: "由玻意耳、查理、盖-吕萨克三条实验定律合并而来。",
            meaning: "一定质量理想气体三个状态量之间的约束关系。",
            limitChecks: [
                LimitCheck(scenario: "体积 V → 一半（温度不变）", result: "压强 → 2 倍", intuition: "打气筒按下去，气体被压、压强升高。"),
                LimitCheck(scenario: "温度 T → 升高（体积不变）", result: "压强 → 升高", intuition: "密闭罐受热会爆，就是这个原因。"),
            ],
            conditions: ["一定质量、理想气体", "温度必须用开尔文 K", "三量同时只能定两个"],
            commonMisuses: ["温度误用摄氏度", "气体质量变化时套用"],
            applications: ["活塞问题", "封闭气柱", "气压计"],
            relatedWeapons: [.controlVariable],
            latex: "\\dfrac{pV}{T} = \\text{常量}"
        ),
        PhysicsLaw(
            id: "photo_equation",
            name: "光电效应方程",
            nameEN: "Photoelectric Equation",
            topic: .modern,
            stage: .senior,
            expression: "Ek = hν − W₀",
            dimension: "J（或 eV）",
            physicalImage: "光子像一颗子弹，能量 hν 砸向电子；先付「逸出费」W₀，剩下的才变成电子的动能。",
            derivation: "爱因斯坦的光量子假说：光以 hν 的能量包传递，对单个电子用能量守恒即得。",
            meaning: "光电子的最大初动能 = 光子能量 − 逸出功。",
            limitChecks: [
                LimitCheck(scenario: "频率 ν → 截止频率（hν=W₀）", result: "Ek → 0", intuition: "刚好够「付费」就能打出电子，但它跑不动。"),
                LimitCheck(scenario: "光强增大（频率不变）", result: "Ek 不变，只是电子更多", intuition: "光强管数量、频率管能量——光电效应的铁律。"),
            ],
            conditions: ["hν > W₀ 才发生", "W₀ 由金属种类决定"],
            commonMisuses: ["以为光强影响最大初动能", "用波动观点解释（解释不了截止频率）"],
            applications: ["光电管", "验证普朗克常量", "截止电压"],
            relatedWeapons: [.energyIntuition],
            latex: "E_k = h\\nu - W_0"
        ),
        PhysicsLaw(
            id: "refraction",
            name: "折射定律",
            nameEN: "Law of Refraction",
            topic: .optics,
            stage: .senior,
            expression: "n = sinθ₁/sinθ₂；全反射 sinC = 1/n",
            dimension: "折射率 n 无量纲",
            physicalImage: "光进入更「密」的介质会变慢、并向法线偏折——像车斜着开进泥地，靠泥一侧先慢，车头就偏了。",
            derivation: "光在不同介质中速度不同（n=c/v），由惠更斯原理或费马原理导出。",
            meaning: "入射角与折射角正弦之比等于折射率，是光速比的体现。",
            limitChecks: [
                LimitCheck(scenario: "光密→光疏，入射角 > 临界角", result: "折射光消失，全反射", intuition: "光纤靠它把光锁在纤芯里，几乎无损耗地传输。"),
                LimitCheck(scenario: "入射角 → 0（垂直入射）", result: "折射角 → 0，不偏折", intuition: "正对着看水里的物体方向不变，只是显得浅。"),
            ],
            conditions: ["两种均匀介质的界面", "角度从法线量起"],
            commonMisuses: ["把全反射方向搞反（必须光密→光疏）", "角度误从界面量起"],
            applications: ["光纤", "海市蜃楼", "玻璃砖测折射率"],
            relatedWeapons: [.symmetry],
            latex: "n = \\dfrac{\\sin\\theta_1}{\\sin\\theta_2},\\quad \\sin C = \\dfrac{1}{n}"
        ),

        // ── 以下为补充条目，覆盖降维秒杀与沙盘高频公式 ──

        PhysicsLaw(
            id: "kinematics",
            name: "匀变速运动三公式",
            nameEN: "Uniformly Accelerated Motion",
            topic: .kinematics,
            stage: .senior,
            expression: "v=v₀+at；s=v₀t+½at²；v²=v₀²+2as",
            dimension: "m/s, m, m/s²",
            physicalImage: "油门踩下去匀加速，速度表匀速往上走，走过的路程越来越多——三个公式是同一段运动从三个角度（速度/位移/无时）描述。",
            derivation: "第一式是加速度的定义：Δv/Δt=a 直接得出。第二式是 v-t 图面积（梯形）。第三式由前两式消去 t 得到，无时公式，解题高频。",
            meaning: "只要 a 不变，这三条关系就成立。已知三个量求第四个——先挑不含无关量的那条公式。",
            limitChecks: [
                LimitCheck(scenario: "a = 0（匀速）", result: "s = v₀t，公式退化为匀速", intuition: "匀速是匀变速的特例，加速度为零时三条公式自动变成中学最基本的关系。"),
                LimitCheck(scenario: "v₀ = 0（从静止开始）", result: "s = ½at²", intuition: "自由落体就是这种情况：s∝t²，每秒走过的路程比是1:3:5:7……"),
            ],
            conditions: ["加速度 a 恒定不变", "取正方向要一致，方向与正方向相反的量取负值"],
            commonMisuses: [
                "v₀ 和 v 搞反（尤其是竖直上抛）",
                "忘记 a 有方向：减速时 a 与 v 反向，a 要取负",
                "三公式只适用于匀变速，变加速不能套",
            ],
            applications: ["自由落体/竖直上抛", "刹车距离", "传送带追及", "斜面运动"],
            relatedWeapons: [.forceDiagram, .graphMethod],
            latex: "v = v_0 + at,\\quad s = v_0t + \\tfrac{1}{2}at^2,\\quad v^2 = v_0^2 + 2as"
        ),

        PhysicsLaw(
            id: "projectile",
            name: "平抛运动分解",
            nameEN: "Projectile Motion",
            topic: .kinematics,
            stage: .senior,
            expression: "x=v₀t；y=½gt²；v=√(vₓ²+vᵧ²)",
            dimension: "m, m/s",
            physicalImage: "从悬崖水平抛出一颗石子——水平方向它匀速飞，竖直方向它自由落，两个独立的运动叠加在一起就是抛物线。",
            derivation: "把运动分成两个独立方向：水平无力→匀速；竖直只有重力→自由落体（初速为零）。两式参数只有 t 是共享的，这就是解题的钥匙。",
            meaning: "合运动 = 分运动的叠加。水平竖直互不干扰，用时间 t 联系两个方向。",
            limitChecks: [
                LimitCheck(scenario: "v₀ = 0（竖直下落）", result: "退化为自由落体 y=½gt²", intuition: "平抛是自由落体的推广——水平速度不影响竖直方向的下落时间。"),
                LimitCheck(scenario: "t 很小（刚离开手时）", result: "轨迹近似直线", intuition: "刚抛出的瞬间，重力还没来得及把它「拽弯」。"),
            ],
            conditions: ["只有重力做功（无空气阻力）", "初速水平", "斜抛时 vₓ=v₀cosθ, vᵧ₀=v₀sinθ"],
            commonMisuses: [
                "混淆水平和竖直公式（水平匀速，竖直才自由落体）",
                "飞行时间由竖直方向决定，与水平速度无关",
                "落地速度要用矢量合成，不能直接相加",
            ],
            applications: ["抛体运动基础题", "平抛射程与角度关系", "运动场跳远测速"],
            relatedWeapons: [.forceDiagram, .referenceFrame],
            latex: "x = v_0 t,\\quad y = \\tfrac{1}{2}gt^2,\\quad v = \\sqrt{v_x^2 + v_y^2}"
        ),

        PhysicsLaw(
            id: "shm_period",
            name: "简谐运动周期公式",
            nameEN: "Period of SHM",
            topic: .wave,
            stage: .senior,
            expression: "弹簧：T=2π√(m/k)；单摆：T=2π√(L/g)",
            dimension: "s",
            physicalImage: "弹簧系统里，质量像「顽固」，弹簧劲度像「急性子」——越重越懒，越硬弹得越快；单摆则是摆长和重力之间的博弈。",
            derivation: "对弹簧：回复力 F=-kx，代入 F=ma 得 ẍ=-(k/m)x，这是角频率 ω=√(k/m) 的简谐运动，T=2π/ω=2π√(m/k)。单摆类比推导。",
            meaning: "周期与振幅无关（等时性），只由系统的「惯性」和「回复力强度」决定。这是简谐运动最反直觉也最重要的结论。",
            limitChecks: [
                LimitCheck(scenario: "弹簧劲度 k → 很大", result: "T → 0（振得很快）", intuition: "超硬弹簧（如钢轨道）振动频率极高。"),
                LimitCheck(scenario: "摆长 L → 4 倍", result: "T → 2 倍", intuition: "T∝√L，摆长变四倍，周期才变两倍。"),
            ],
            conditions: ["小振幅（单摆 θ<5°）", "弹簧轻质、弹性限度内", "忽略阻尼"],
            commonMisuses: [
                "以为振幅大周期就大（等时性：振幅不影响周期）",
                "单摆在月球上周期变长（g 小，T=2π√(L/g) 变大）",
                "弹簧劲度 k 与弹簧长短有关：弹簧越短越硬",
            ],
            applications: ["计时摆钟", "弹簧测力计标定", "共振频率匹配"],
            relatedWeapons: [.energyIntuition, .symmetry],
            latex: "T = 2\\pi\\sqrt{\\dfrac{m}{k}},\\quad T = 2\\pi\\sqrt{\\dfrac{L}{g}}"
        ),

        PhysicsLaw(
            id: "electric_field",
            name: "电场强度公式",
            nameEN: "Electric Field Strength",
            topic: .electricField,
            stage: .senior,
            expression: "E = F/q（定义式）；E = kQ/r²（点电荷）；E = U/d（匀强）",
            dimension: "N/C = V/m",
            physicalImage: "放一个正「探针电荷」q 进来，它受到多大力，那个力除以 q 就是电场强度——E 描述的是这块空间有多「电」，跟 q 无关。",
            derivation: "E=F/q 是定义，用探测电荷的受力来量化空间中的电场。点电荷的 E 由库仑定律直接得到（F=kQq/r²，除以 q）。",
            meaning: "E 是场的性质，不依赖于探测电荷 q 的大小；E 的方向就是正电荷受力方向。",
            limitChecks: [
                LimitCheck(scenario: "平行板电容器 d→0（极板靠近）", result: "E=U/d → 无穷大", intuition: "同样电压，极板越近电场越强——击穿空气就靠这个原理。"),
                LimitCheck(scenario: "距点电荷 r→很远", result: "E→0", intuition: "电场随距离平方衰减，离得足够远就感受不到了。"),
            ],
            conditions: [
                "E=F/q 要用小探测电荷（不能影响源场）",
                "E=U/d 只在匀强电场（平行板间）成立",
                "E = kQ/r² 只适用于点电荷",
            ],
            commonMisuses: [
                "把 E=U/d 用在非匀强电场",
                "认为 q 越大 E 越大——E 与 q 无关",
                "方向：负电荷受力与 E 相反",
            ],
            applications: ["平行板电容器", "带电粒子在电场中偏转（类平抛）", "电场线密度反映 E 大小"],
            relatedWeapons: [.equivalentMethod, .workEnergyTheorem],
            latex: "E = \\dfrac{F}{q} = \\dfrac{kQ}{r^2} = \\dfrac{U}{d}"
        ),

        PhysicsLaw(
            id: "capacitor",
            name: "电容公式",
            nameEN: "Capacitance",
            topic: .electricField,
            stage: .senior,
            expression: "C = Q/U；平行板 C = ε₀S/d",
            dimension: "F（法拉）= C/V",
            physicalImage: "电容就是「储电量/电压」——同样的电压，塞进去的电荷越多，电容越大；平行板像两块充电的煎饼，越大越近越能「存电」。",
            derivation: "C=Q/U 是定义式。对平行板，E=U/d，又 E=σ/ε₀=Q/(ε₀S)，联立得 C=ε₀S/d。",
            meaning: "电容是「容量」，描述在单位电压下能存多少电荷，由几何结构决定，与 Q、U 无关。",
            limitChecks: [
                LimitCheck(scenario: "极板间距 d → 2 倍", result: "C → ½；若 Q 不变，U → 2 倍", intuition: "两极板离开，储电能力下降，电压升高。"),
                LimitCheck(scenario: "充电后断电（Q 不变），再增大 d", result: "C 减小，U=Q/C 升高，E=U/d 不变", intuition: "断电后 Q 被锁住，电场不变，但电压随间距增大——重要考点！"),
            ],
            conditions: ["C=ε₀S/d 只适用于平行板、真空/空气", "实际有介质时 C=εS/d"],
            commonMisuses: [
                "C=Q/U 中 C 不随 Q、U 变化（Q/U 的比值才是 C）",
                "「断电后」与「接电源」两种情境下动态分析结论完全不同",
                "C 越大不代表电场越强（E 由 U/d 决定）",
            ],
            applications: ["电容器充放电动态分析", "RC 电路时间常数 τ=RC", "触摸屏原理"],
            relatedWeapons: [.controlVariable, .equivalentMethod],
            latex: "C = \\dfrac{Q}{U} = \\dfrac{\\varepsilon_0 S}{d}"
        ),

        PhysicsLaw(
            id: "transformer",
            name: "理想变压器公式",
            nameEN: "Ideal Transformer",
            topic: .induction,
            stage: .senior,
            expression: "U₁/U₂ = n₁/n₂；I₁/I₂ = n₂/n₁；P₁ = P₂",
            dimension: "U: V；I: A；P: W",
            physicalImage: "变压器是「力矩放大器」的电学版——匝数多的一侧电压高、电流小；匝数少的一侧电压低、电流大；功率不增不减，能量守恒。",
            derivation: "基于法拉第定律：两线圈切割的是同一磁场，每匝感应电压相同，总电压之比就是匝数之比。能量守恒给出电流比是匝数比的倒数。",
            meaning: "变压器改变的是电压和电流，不改变功率（理想条件下）。升压→降流，降压→升流。",
            limitChecks: [
                LimitCheck(scenario: "n₁=n₂（匝数相同）", result: "U₁=U₂，I₁=I₂，像导线直连", intuition: "1:1 变压器本质上不变，但可以起电气隔离作用。"),
                LimitCheck(scenario: "副线圈开路（I₂=0）", result: "I₁≈0，功率≈0", intuition: "空载变压器几乎不耗电——这是理想情况，实际有磁化损耗。"),
            ],
            conditions: ["理想变压器：无漏磁、线圈电阻为零、无铁损", "公式中 I₁/I₂=n₂/n₁ 仅在有负载时成立（开路时 I₁≠0 不适用）"],
            commonMisuses: [
                "开路时也套 I 的比值公式",
                "多副线圈时混用电流比（应分别对每个副线圈用 P 守恒）",
                "忘记升压变压器的初级匝数少、次级匝数多",
            ],
            applications: ["远距离输电（升压减少线路损耗）", "手机充电器降压", "焊机大电流低压"],
            relatedWeapons: [.lenzRule, .energyIntuition],
            latex: "\\dfrac{U_1}{U_2} = \\dfrac{n_1}{n_2},\\quad \\dfrac{I_1}{I_2} = \\dfrac{n_2}{n_1},\\quad P_1 = P_2"
        ),

        PhysicsLaw(
            id: "wave_speed",
            name: "波速公式",
            nameEN: "Wave Speed",
            topic: .wave,
            stage: .senior,
            expression: "v = λf = λ/T",
            dimension: "m/s",
            physicalImage: "波是「形状」在空间里跑，不是介质在跑——浮在水面的软木塞只是上下抖，水波的「图案」却在向外传播。",
            derivation: "每个周期 T，波向前传播一个波长 λ；速度 = 路程/时间 = λ/T = λf。",
            meaning: "波速由介质决定（不由频率决定！）；频率由声源决定；波长是两者共同决定的结果。",
            limitChecks: [
                LimitCheck(scenario: "频率 f 升高（同一介质）", result: "v 不变，λ = v/f 减小", intuition: "同一根绳子，振得更快，波长变短，但波速不变——这是波动最反直觉的地方。"),
                LimitCheck(scenario: "声音从空气进入水", result: "v 增大，f 不变，λ 增大", intuition: "频率是声源决定的，不会因为介质变了而变——所以水里声音波长更长。"),
            ],
            conditions: ["机械波：v 由介质的弹性和密度决定", "电磁波：真空中 v=c=3×10⁸ m/s", "同一介质同一频率，v 与振幅无关"],
            commonMisuses: [
                "以为频率高波速就快（波速与频率无关）",
                "多普勒效应时频率变了，介质中波速没变",
                "v=λf 中的 v 和 λ 要在同一介质中取值",
            ],
            applications: ["声纳测距", "多普勒测速", "驻波条件 L=nλ/2"],
            relatedWeapons: [.graphMethod, .symmetry],
            latex: "v = \\lambda f = \\dfrac{\\lambda}{T}"
        ),

        PhysicsLaw(
            id: "mass_energy",
            name: "质能方程",
            nameEN: "Mass–Energy Equivalence",
            topic: .modern,
            stage: .senior,
            expression: "E = mc²；ΔE = Δmc²",
            dimension: "J；1 u = 931.5 MeV/c²",
            physicalImage: "质量就是「浓缩的能量」——一丁点质量亏损（原子核层面），乘以光速的平方（9×10¹⁶），就是巨大的能量。铀弹、氢弹的破坏力都来源于这个 c²。",
            derivation: "狭义相对论的核心结论：物体静止时也有能量 E₀=mc²。核反应中质量减少（质量亏损），这部分质量完全转化为能量释放出来。",
            meaning: "质量和能量是同一事物的两种度量，可以相互转化。核反应的能量来源就是反应前后的质量差。",
            limitChecks: [
                LimitCheck(scenario: "Δm = 1 u ≈ 1.66×10⁻²⁷ kg", result: "ΔE = Δmc² ≈ 931.5 MeV", intuition: "高考必记换算：1 u 的质量亏损对应 931.5 MeV 的能量。"),
                LimitCheck(scenario: "化学反应（原子层面）", result: "质量变化极小（10⁻¹²量级）", intuition: "化学反应也有质量亏损，但太小测不出来——只有核反应的亏损才显著。"),
            ],
            conditions: ["Δm 用原子质量单位 u 时，ΔE（MeV）= Δm(u) × 931.5", "核反应中质子数和中子数守恒，但不是质量守恒"],
            commonMisuses: [
                "把「质量数守恒」误以为「质量守恒」——核反应中真实质量（不是质量数）不守恒",
                "裂变/聚变都有质量亏损，但聚变亏损比例更大",
                "ΔE = Δmc² 中 c=3×10⁸ m/s，算出来单位是 J",
            ],
            applications: ["核电站裂变能量计算", "聚变反应堆", "医用正电子湮灭扫描（PET）"],
            relatedWeapons: [.energyIntuition, .dimensionalAnalysis],
            latex: "E = mc^2,\\quad \\Delta E = \\Delta m \\cdot c^2"
        ),

        PhysicsLaw(
            id: "lens_formula",
            name: "薄透镜公式",
            nameEN: "Thin Lens Equation",
            topic: .optics,
            stage: .senior,
            expression: "1/u + 1/v = 1/f；放大率 m = v/u",
            dimension: "cm 或 m",
            physicalImage: "透镜让来自物点的发散光重新汇聚成像——物距（物到镜）和像距（像到镜）之间有严格的倒数关系，焦距是连接它们的桥梁。",
            derivation: "由光路的折射定律和相似三角形推出，是几何光学的核心公式。",
            meaning: "已知焦距和物距，就能算出成像位置。u=2f 时 v=2f（等大实像）；u<f 时 v 为负（虚像，正立放大）。",
            limitChecks: [
                LimitCheck(scenario: "u = f（物在焦点上）", result: "1/v = 0，v → ∞，平行光出射", intuition: "手电筒聚光——灯在焦点处，出射平行光束。"),
                LimitCheck(scenario: "u < f（物在焦点内）", result: "v 为负，虚像正立放大", intuition: "放大镜的原理：物比焦距近，像在同侧，正立放大。"),
            ],
            conditions: ["薄透镜近轴光线", "实物实像时 u>0, v>0；虚像 v<0", "凸透镜 f>0；凹透镜 f<0"],
            commonMisuses: [
                "搞混实像与虚像的符号规则",
                "凹透镜只成缩小正立虚像，不成实像",
                "放大率 m=v/u，m>1 放大，m<1 缩小，m 为负时倒立",
            ],
            applications: ["照相机（u>2f）", "投影仪（f<u<2f）", "放大镜（u<f）", "眼镜矫正"],
            relatedWeapons: [.symmetry, .graphMethod],
            latex: "\\dfrac{1}{u} + \\dfrac{1}{v} = \\dfrac{1}{f},\\quad m = \\dfrac{v}{u}"
        ),

        PhysicsLaw(
            id: "bohr_energy",
            name: "玻尔能级公式",
            nameEN: "Bohr Energy Levels",
            topic: .modern,
            stage: .senior,
            expression: "Eₙ = E₁/n²（氢原子 E₁ = −13.6 eV）",
            dimension: "eV（电子伏）",
            physicalImage: "原子里的电子不能在任意轨道上待，只能在特定的「台阶」上——越往外台阶能量越高，跳下来就放出光子，跳上去就吸收光子，不多不少。",
            derivation: "玻尔假设：轨道角动量量子化 L=nħ；库仑力提供向心力。联立得出轨道半径 rₙ=n²r₁，能量 Eₙ=E₁/n²。",
            meaning: "氢原子能级是分立的，光谱线来自能级之间的跃迁，每根谱线对应一个固定的 ΔE=hν。",
            limitChecks: [
                LimitCheck(scenario: "n → ∞", result: "Eₙ → 0，电子逃出原子（电离）", intuition: "第 n 能级能量是 −13.6/n² eV，n 越大能量越趋近 0，直到脱离束缚。"),
                LimitCheck(scenario: "n=1 到 n=2（最低跃迁）", result: "ΔE=10.2 eV，紫外线", intuition: "氢原子最低能级跳到第二级需要 10.2eV，在紫外区——肉眼看不见。"),
            ],
            conditions: ["只对氢原子（单电子）精确适用", "多电子原子的能级更复杂", "辐射公式 hν=E高-E低"],
            commonMisuses: [
                "从高能级跳到低能级是辐射（放出光子），反之是吸收",
                "跃迁对应的光子能量 hν=|ΔE|，不是 E 本身",
                "第 n 能级的能量是负值（束缚态），越负越稳定",
            ],
            applications: ["氢原子光谱线分系（莱曼、巴尔末系）", "激光原理", "X 射线特征谱"],
            relatedWeapons: [.energyIntuition, .dimensionalAnalysis],
            latex: "E_n = \\dfrac{E_1}{n^2},\\quad E_1 = -13.6\\,\\text{eV},\\quad h\\nu = E_m - E_n"
        ),
    ]

    static func laws(for topic: PhysicsTopic) -> [PhysicsLaw] {
        all.filter { $0.topic == topic }
    }
}
